services:
  - type: web
    name: naotin-students-app
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true